### ISSUE TITLE
unable to locate annotation results

### ISSUE THREAD

**Issue by prasannabhat** [yuzutech/annotations-action#1]
I am trying to integrate this action into a workflow. I could see that action finishes successfully, however I cant see the annotation [results](https://github.com/prasannabhat/iceoryx/actions/runs/398083343).

I assume I can see the results in `Annotations` section in `Actions` tab.

**Comment by Mogztter** [comment]
Not sure exactly why but the run id was not associated with the current run:

```
Updating check {owner: 'prasannabhat', repo: 'iceoryx', check_run_id: 1491778842}
```

https://github.com/prasannabhat/iceoryx/runs/1491778842

The [create checks API from GitHub](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#create-a-check-run) is a bit mysterious since you cannot assign it to a given job or run...

**Comment by Mogztter** [comment]
It's also worth noting that the current run id cannot be retrieve from an action :disappointed: 
Alternatively, we could use `octokit.checks.listForRef()` but it's also unreliable since it can return more than one result...

**Comment by Mogztter** [comment]
For reference, a "check run" is associated to a commit.
I can see in the checkout task of the run id [1491777786](https://github.com/prasannabhat/iceoryx/runs/1491777786) that the ref was:

```
/usr/bin/git log -1 --format='%H'
'7dbdc448fe4f2c0beb5ee7ef0b534cc7c972e413'
```

Unfortunately, the run id [1491778842](https://github.com/prasannabhat/iceoryx/runs/1491778842) is also using this ref:

![run-ref](https://user-images.githubusercontent.com/333276/101542895-be4b7200-39a3-11eb-9ccd-1a8fc0ed31aa.png)


As far as I know this is inherent to the GitHub API.
I've asked [this question](https://github.community/t/how-to-reliably-attach-a-check-run-to-the-current-run/147719) on the GitHub Support Community, hopefully someone will provide a solution.

**Comment by Mogztter** [comment]
@prasannabhat Could you please try again with the latest release, the annotations should now be correctly attached to the pull request: https://github.com/yuzutech/annotations-action/releases/tag/v0.2.1

**Comment by prasannabhat** [comment]
@Mogztter Thank you very much for the updates.
I will try in a couple of days.

**Comment by prasannabhat** [comment]
@Mogztter works now ! Thanks 
https://github.com/prasannabhat/iceoryx/actions/runs/427162103

**Comment by Mogztter** [comment]
Awesome 👍 
Closing this issue...
