### ISSUE TITLE
Error - not found

### ISSUE THREAD

**Issue by pun-ky** [yuzutech/annotations-action#13]
any hints? :)

![](https://user-images.githubusercontent.com/10673561/107778321-3dfb1180-6d44-11eb-9381-7e291d4fe1b5.png)

**Comment by Mogztter** [comment]
@pun-ky `Not Found` means that the GitHub API returns a 404. Most of the time it indicates that the token does not have the permission to read (or write) on the repository.

**Comment by pun-ky** [comment]
or I provided object instead of array :)
