### ISSUE TITLE
Annotations not attaching to changed files

### ISSUE THREAD

**Issue by cmsj** [yuzutech/annotations-action#19]
I've set up this action on two repos and while one is working perfectly, on the second one I'm seeing the annotations in the output of a PR workflow, but they're not being displayed in-line with the changed files, and I can't figure out what the issue is.

https://github.com/Hammerspoon/Spoons/pull/230 is an example PR to show this.

Hopefully you can see https://github.com/Hammerspoon/Spoons/pull/230/checks?check_run_id=2292390023 which shows the two expected annotations, but they aren't shown on https://github.com/Hammerspoon/Spoons/pull/230/files

I would very much appreciate any suggestions!

**Comment by cmsj** [comment]
<img width="1397" alt="Screenshot 2021-04-08 at 01 11 53" src="https://user-images.githubusercontent.com/353427/113949533-6b75b000-9807-11eb-83b1-f78e7b318d32.png">

(just in case you can't see the second link there)

**Comment by Mogztter** [comment]
Hey @cmsj 

I think it only works if the line has changed in the commit. Here line 64 and 45 were not updated.
Please note that the annotations API has several flaws. I wish I had more control but we have limited options 😞

**Comment by cmsj** [comment]
Thanks for the reply, I can live with that, and hope that one day the Annotations API will improve :)
