### ISSUE TITLE
Getting error `cause: HttpError: You must authenticate via a GitHub App.`

### ISSUE THREAD

**Issue by tahirmt** [yuzutech/annotations-action#37]
Hi I'm getting an error `cause: HttpError: You must authenticate via a GitHub App.` when using this action.

My json file is like this

```
[{"file":"path/to/file","line":12,"title":"Some error title","message":"some error message","annotation_level":"failure"}]
```
Here is the log from the run

```
Run yuzutech/annotations-action@v0.3.0
  with:
    repo-token: ***
    input: ./annotations.json
    title: Build report
    ignore-unauthorized-error: false
    ignore-missing-file: true
Creating check {owner: '<owner>', repo: '<repo>', name: Report}
Error: GitHubApiError: Unable to create a check to '<owner>/<repo>' - cause: HttpError: You must authenticate via a GitHub App.
```

Am I missing something?

**Comment by Mogztter** [comment]
Hello,

Maybe it's related to: https://github.com/yuzutech/annotations-action/issues/5

> Usually this error indicates a permission issue. Check that your PAT has write access to the repository.
Did you try with the built-in token repo-token: `${{ secrets.GITHUB_TOKEN }}`?
Are you trying to create annotations from a fork?

**Comment by tahirmt** [comment]
@Mogztter thank you for the answer. My personal access token has write access to the repo. I use it to make pushes in other workflows. The repo is a private repo which is not forked.

**Comment by tahirmt** [comment]
Looks like using the GitHub token works. Not sure what’s wrong with my personal access token then.

**Comment by tahirmt** [comment]
@Mogztter can I use `start_line` and `end_line` instead of `line`?

**Comment by Mogztter** [comment]
@tahirmt Yes, it should work
