### ISSUE TITLE
Can't get this action working (Error: GitHubApiError: Unable to create a check to 'repo' - cause: HttpError: You must authenticate via a GitHub App.)

### ISSUE THREAD

**Issue by Yoshinonxkun** [yuzutech/annotations-action#5]
Hi,

We are Building a .vue-App in our university course and I am try to get this workflow working.

What will I do:
I run yarn lint and parse the output to a file like:
![image](https://user-images.githubusercontent.com/45177922/102693323-12fbb200-421a-11eb-85ed-96dd8483f20a.png)

and then I want to upload the annotations with your workflow:
![image](https://user-images.githubusercontent.com/45177922/102693597-0b3d0d00-421c-11eb-9687-37ea16a25b17.png)

The script:
![image](https://user-images.githubusercontent.com/45177922/102693363-6110b580-421a-11eb-829c-f0848d89a59b.png)

API_TOKEN_GITHUB is my PAT

We have our own organization created for our project and our repo is currently private, because it is in developing state.

Why we have this Error?

**Comment by Mogztter** [comment]
Hi,

Usually this error indicates a permission issue. Check that your PAT has write access to the repository.
Did you try with the built-in token `repo-token: ${{ secrets.GITHUB_TOKEN }}`?

Are you trying to create annotations from a fork?

**Comment by Yoshinonxkun** [comment]
Thanks!
I didn't noticed that this token is built-in.

Now it works!
